[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
iced = { version = "0.14.0", features = ["highlighter", "hot"] }
iced_aw = "0.13.0"
tracing-subscriber = "0.3.22"
core = { path = "../core" }
