[package]
name = "gpui"
version.workspace = true
edition.workspace = true

[dependencies]
tracing-subscriber = "0.3.22"
gpui = "0.2.2"
gpui-component = "0.5.0"
gpui-component-assets = "0.5.0"
core = { path = "../core" }
