name: Rust

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --release
    - name: Remove .d files
      run: rm target/release/*.d
    - name: Save executables
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: |
          target/release/cli
          target/release/gui

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --release
    - name: Remove .d files
      run: rm target/release/*.d
    - name: Save executables
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: |
          target/release/cli*
          target/release/gui*
          
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --release
    - name: Remove .d files
      run: rm target/release/*.d
    - name: Save executables
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: |
          target/release/cli
          target/release/gui

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get all build outputs
        uses: actions/download-artifact@v4
        with:
          path: exec/

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: JTool
          prerelease: true
          generate_release_notes: true
          files: |
            exec/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/jtool
